apiVersion: v1
kind: Pod
metadata:
   name: nishanth-jenkins-pod
spec:
   containers:
   - name: jenkisn-con
     image: nishanth00/hello-world-0.2-snapshot
     ports:
     - containerPort: 9595