apiVersion: apps/v1
kind: Deployment
metadata:
   name: k8simage
spec:
   containers:
   - name: k8simages
     image: nishanth00/hello-world-0.2-snapshot
     ports:
     - containerPort: 9590
